### ISSUE TITLE
Not working with extra Payload plugins?

### ISSUE THREAD

**Issue by cor-emble** [payloadcms/next-payload#12]
Hi!

We're building a new website in Next.js and Payload and are testing this awesome looking plugin. We've followed the readme docs and have it fully working now, but we're running into issues when we add a Payload plugin like the SEO or Formbuilder plugin. 

The error we got is: 

`You're importing a component that needs unstable_batchedUpdates. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.`

Which, if i understand it correctly, means we have to make the whole Next.js app client side? 

Are we doing something wrong?

**Comment by jmikrut** [comment]
Hey @cor-emble — good catch! I thought that we had this solved by adding `use client` to the top of the Payload admin `page.tsx` file, but apparently we needed to add it to Payload's root admin UI component as well.

We are about to release a new version of Payload, at which point, this will be resolved. It's already added / fixed in Payload core and will be coming alongside of some other updates to this package itself!
