### ISSUE TITLE
Large number of connections MongoDB Atlas

### ISSUE THREAD

**Issue by rpfaeffle** [payloadcms/next-payload#15]
When deploying to vercel, payload creates a new connection to mongodb for every serverless function call. Therefore and due to the fact that those are not closed after the function has executed the number of connections with Atlas is pretty big.

For instance just when having opened an edit view payload reaches 100 connections and when building the actual website and making API calls to the graphql enpoint the number of connections easily exceeds 500.

**Comment by jmikrut** [comment]
Hmmmm this is certainly interesting. We currently _**do**_ cache connections per serverless function, and that happens within Payload itself. See here:

https://github.com/payloadcms/payload/blob/master/src/payload.ts#L410

I'd expect this to resolve this max connections issue but apparently it's not bulletproof. And reading online, it looks like LOTS of people have issues with Vercel / Next in general with max database connections (including Atlas) but there is no straightforward "fix".

Some people report that caching as we do in Payload works, but others report that they still have the issue.

We will be digging into this further, but if you're interested in helping, I'd say that one thing to try and do is to _**move out**_ the caching of Payload itself into your own `payload.ts` file, and cache there, instead of relying on the package to cache for us. Will you try that?

In principle, it'd be following a guide like these:

https://www.mongodb.com/developer/languages/javascript/integrate-mongodb-vercel-functions-serverless-experience/
https://github.com/vercel/next.js/blob/canary/examples/with-mongodb-mongoose/lib/dbConnect.js

But instead of caching the Mongo connection, the idea would be to cache the entire Payload initialization.

What's funny also is that I have tested with adding a `console.log` to every time that Payload initializes, and it's clear that it is only initializing once and properly caching within subsequent lambda invocations... so it does appear that caching is working.

We will keep digging here. If you do as well, I would greatly appreciate it!

**Comment by rpfaeffle** [comment]
Thanks for the quick reply.

I updated my code to cache Payload itself in the `payload.ts` file and it seems to have somehow fixed the issue. The number of connections still reaches somewhat of about 100 but did not reach 500 like it did without caching payload itself.

I will keep an eye on it and keep digging when I find the time.

**Comment by JarrodMFlesch** [comment]
@rpfaeffle I am going to close this issue, I added this improvement to the project itself [here](https://github.com/payloadcms/next-payload/blob/main/templates/payloadClient.ts#L19).
