### ISSUE TITLE
getPayloadClient doesn't work

### ISSUE THREAD

**Issue by NardiniA** [payloadcms/next-payload#27]
The Payload admin system works when when trying to use the Payload Client to query the database, it throws an error saying it is using a client-side package "use-context-selector". This means it cannot be used to query content and because of it's access to the database it cannot be used with "use client". 

My code for this is [here](https://github.com/NardiniA/next-payload-serverless).

**Comment by JarrodMFlesch** [comment]
Hey @NardiniA thanks for bringing this to our attention. The fix was to add `use client` to the top of the custom react components created within the plugins you are using `@payloadcms/plugin-seo` & `@payloadcms/plugin-form-builder`.

I opened 2 PRs, one for each. Once a new version of each one is released you will be able to install them and continue on 👍

**Comment by NardiniA** [comment]
Hi @JarrodMFlesch, thanks for sorting the packages but I think `@payloadcms/plugin-form-builder` (v1.0.14) hasn't been built because it does not have a `dist` folder in my `node_modules`.

**Comment by JarrodMFlesch** [comment]
0.0.23 does not exist yet. When a release is cut I will close this again.

**Comment by JarrodMFlesch** [comment]
Fixed in latest
