### ISSUE TITLE
Payload Routes Breaks on Nextjs

### ISSUE THREAD

**Issue by okeken** [payloadcms/next-payload#44]
For example a user triggers, forgot and got a typical link like below,

http://localhost:3000/dashboard/reset/d85b566d3bb185001968d9df27ea767d7d70ead5

On navigating to the frontend, nextjs returns a 404 page, what's the best way to make sure nextjs is aware of this route?

**Comment by imCorfitz** [comment]
When initialising the `next-payload` package, you will noticed that in your `app` directory will be created a group folder called `(payload)` inside which is a folder called `admin` which is the route set by payload by default. 

Inside your `next.config.ts` file you are then asked to wrap your config in the `withPayload` helper. This wrapper sets a few next.config parameters for you, one of which is the handling of all routes on the `admin` path. 

The reason you get 404 is likely that you attempt to use `dashboard` as your admin route, but the configuration isn't set up to match this path.

**Comment by JarrodMFlesch** [comment]
I am going to close this issue @okeken. I believe @imCorfitz is correct, unless you manually changed the folder name inside `app/(payload)/admin` to `app/(payload)/dashboard` **and** adjusted your payload config's admin path to match this.

Also note that the reset password url is `/reset-password` not `/reset`

**Comment by okeken** [comment]
@JarrodMFlesch correct, I changed the (payload)/admin to match the admin route in my payload.config.ts file, is there a way to use a custom name other than admin,  I'm using it for a web app, where the dashboard is also being being used by the end users.

**Comment by imCorfitz** [comment]
You might also need to set the rewrite in `next.config.js`. I have created a PR that enables you to set the custom path as part of the `withPayload` config, and some documentation along with it. #47 

But basically, the `withPayload` wrapper in `next.config.js` creates a `rewrite` config which forwards all routes on `/admin/*` to the `page.tsx` in `/app/(payload)/admin`. In order to change this, you would need to add a custom rewrite object to your `next.config.js` which says something like 

```ts
{
   rewrite: [
       {
           source: "/dashboard/:path*",
           destination: "/dashboard",
       }
   ]
}
```

**Comment by JarrodMFlesch** [comment]
oh @imCorfitz nice! I will check that out and a couple other outstanding PR's here as well today.
