### ISSUE TITLE
Unexpected handler pages/api/[collection]/lib/worker.js in next-payload

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/next-payload#97]
### Link to reproduction

 https://github.com/Stupidism/sunmer/tree/feature/add-payload-integration

### Describe the Bug

Looks like payload has some new handlers, but next-payload doesn't support?

```
error uncaughtException: Error: Cannot find module '/Users/sun/Documents/personal/sunmer/apps/steps/.next/server/pages/api/[collection]/lib/worker.js'
```

<img width="750" alt="image" src="https://github.com/payloadcms/next-payload/assets/5801015/86732acb-60f9-4363-84c0-3daba4c1acbe">

Repro repo: https://github.com/Stupidism/sunmer/tree/feature/add-payload-integration

### To Reproduce

```
git clone git@github.com:Stupidism/sunmer.git
git checkout feature/add-payload-integration
pnpm install
nx run steps:serve
open http://localhost:4200/admin
```

### Payload Version

2.1.1

### Adapters and Plugins

none

**Comment by ghardin1314** [comment]
`this.config.db is not a function` is coming because you did not configure a db in your `payload.config.ts` file. This is a new thing in v2 (if you used v1 before) and not handled well by the template this repo sets up for you. See docs on how to configure:

https://payloadcms.com/docs/database/overview

p.s. you also need to configure an editor too (also not handled by the setup template)

https://payloadcms.com/docs/rich-text/overview
